### ISSUE TITLE
don't set status on vk.com

### ISSUE THREAD

**Issue by geniyz** [lnussbaum/xmpp4r#12]
code:

<pre>
require "rubygems"
require "xmpp4r"
client = Jabber::Client.new(Jabber::JID.new('geniyz@vk.com'))
client.connect
client.auth('MyPassword')
client.send(Jabber::Presence.new.set_type(:available))
client.send(Jabber::Presence.new.set_status('bla-bla-bla'))
client.close 
</pre>

works without errors,
but don't change status in vk.com
normal change status only if run this script line-by-line in irb

**Comment by mironov** [comment]
You should use .set_show instead of .set_type in order to set status. See [docs](http://home.gna.org/xmpp4r/rdoc/classes/Jabber/Presence.html#M000702).
Also you can pass status as parameter to Presence.new (see below).

And try to sleep for a second before closing connection:

```
require "rubygems"
require "xmpp4r"
client = Jabber::Client.new(Jabber::JID.new('geniyz@vk.com'))
client.connect
client.auth('MyPassword')
client.send(Jabber::Presence.new(nil, 'bla-bla-bla'))
sleep 1
client.close
```

**Comment by geniyz** [comment]
Thanks, it's be working!!
