### ISSUE TITLE
100% cpu usage when karma gets low?

### ISSUE THREAD

**Issue by futurechimp** [lnussbaum/xmpp4r#23]
Hi, 

I'm experiencing a problem where my web app servers periodically lock up at 100% CPU when using xmpp4r.  

I've made a gist to repro the problem:

https://gist.github.com/1197232

Basically, I think what's happening is that under conditions of either high latency (due to bad connections) or high concurrency (especially when a user's karma is low causing rate-limiting at the server end), xmpp4r is sitting and waiting for a lock inside lib/xmpp4r/semaphore.rb on line 24.  

Messages _are_ eventually delivered reliably by xmpp4r, so there wouldn't be a big problem, except for the high CPU load.  

Or maybe I am doing something wrong?

**Comment by astro** [comment]
I'm not active on xmpp4r anymore, but two hints:
- Try to retain the XMPP connection, don't set it up for each request
- If possible, switch to an asynchronous programming model (ie. EventMachine). You may have to hack xmpp4r to bring back asynchronous capabilities.

**Comment by futurechimp** [comment]
Hi astro, thanks for the help.  I was thinking along the same lines, of taking the xmpp sending out-of-process using something like resque.  I'll also try connection re-use and see what happens.

**Comment by futurechimp** [comment]
Astro, thanks, fixing connection pooling worked great, no need to take anything out-of-process with a queueing solution.  ab benchmarks now do 750 messages per second or so, with no appreciable CPU load.  So, this gist documents it:

https://gist.github.com/1197857

Thanks for the help and sorry to file a spurious bug report.  Closing.

**Comment by astro** [comment]
Congratulations on your solution. It's great to see xmpp4r still being used successfully.
